services:
  db:
    image: postgres:16-alpine
    container_name: pg_db_dev
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: nest_api_dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env.dev
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: vite_web_dev
    ports:
      - "5173:5173"
    environment:
      # Vite użyje tego na etapie build/runtime w przeglądarce
      # Z poziomu PRZEGLĄDARKI backend jest pod localhost:3000
      - VITE_API_URL=${VITE_API_URL-http://localhost:3000}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api

volumes:
  db_data_dev:
